### ISSUE TITLE
lightspark not compiling?

### ISSUE THREAD

**Issue by Xylemon** [PhantomX/slackbuilds#11]
Having an odd issue, and I'm pretty sure I have all the dependencies installed, but I'm trying to compile lightspark with your SlackBuild and it fails near the end of the compile with:

"in/ld: cannot find -lLLVM-3.3"

Any ideas?

**Comment by Xylemon** [comment]
Now this is odd, I was trying this again to see if this was still a problem when Lightspark failed to compile (again):

 -c /tmp/lightspark-0.7.2/src/scripting/abc.cpp
/tmp/lightspark-0.7.2/src/scripting/abc.cpp:38:30: fatal error: llvm/IR/Verifier.h: No such file or directory
 #include <llvm/IR/Verifier.h>
                              ^
compilation terminated.
make[2]: *** [src/CMakeFiles/spark.dir/scripting/abc.cpp.o] Error 1
make[2]: Leaving directory `/tmp/lightspark-0.7.2/build'
make[1]: *** [src/CMakeFiles/spark.dir/all] Error 2
make[1]: Leaving directory `/tmp/lightspark-0.7.2/build'
make: *** [all] Error 2

**Comment by PhantomX** [comment]
I tested with llvm 3.5.0 only. Try again without fix-for-llvm35.patch.

**Comment by Xylemon** [comment]
Ok tried your LLVM 3.5 SlackBuild, and it finally compiled. It does compile a library to "/usr/lib64/mozilla/plugins" however it's still not detected by Firefox or Seamonkey. I also tried the latest git (which actually doesn't need any of the patches that 0.7.2 needed) and same result. I shouldn't need xulrunner right? I know of other Mozilla plugins that require that to be compiled..

**Comment by PhantomX** [comment]
Yes, all packages with browser plugins make extra packages for them, that way is possible install plugins without conflicts.
