### ISSUE TITLE
gdk-pixbuf SlackBuild is broken

### ISSUE THREAD

**Issue by Xylemon** [PhantomX/slackbuilds#19]
Under the _pasture section, the slackbuild for gdk-pixbuff fails with the error:

	cp: cannot stat '/usr/share/automake/config.guess': No such file or directory                           
	cp: cannot stat '/usr/share/automake/config.sub': No such file or directory

I do have automake14 and autoconf213 installed. Any help?

**Comment by PhantomX** [comment]
Things from _pasture aren't supported, but this can be fixed with latest automake. Slackware current have 1.14.1 version, I have 1.15.

**Comment by Xylemon** [comment]
Ah that worked, thanks!
