### ISSUE TITLE
ARandR failes to compile

### ISSUE THREAD

**Issue by Xylemon** [PhantomX/slackbuilds#20]
When trying to compile, I get:

Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    import docutils.core
ImportError: No module named docutils.core

**Comment by PhantomX** [comment]
Missing python-docutils.

**Comment by Xylemon** [comment]
Alright, it should be in the slack-required document then.

**Comment by PhantomX** [comment]
I just document runtime dependencies in slack-required files.
