### ISSUE TITLE
Linux Kernel 4.0 OSS4.2 Patch

### ISSUE THREAD

**Issue by Xylemon** [PhantomX/slackbuilds#22]
Here's a patch for OSS4.2 that fixes compiling for the 4.0 kernel: http://4front-tech.com/forum/viewtopic.php?f=3&t=5800&sid=df34d95d30eb546f0d59703afe16ef09

Although you don't have a kernel custom slackbuild for 4.0, I'm sure it'll come to use very soon.

**Comment by PhantomX** [comment]
Commited 2 days ago. :)
https://github.com/PhantomX/slackbuilds/tree/master/kernel-custom
https://github.com/PhantomX/slackbuilds/tree/master/kernel-kmod/kmod-oss-custom/patches

**Comment by Xylemon** [comment]
Oh haha, my local copy was outdated. Sorry!
