### ISSUE TITLE
Libclc fails on LLVM 3.6.0

### ISSUE THREAD

**Issue by Xylemon** [PhantomX/slackbuilds#23]
Get the following compiling error:

./generic/include/clc/integer/abs.inc:1:41: note: 'abs' is a builtin with type 'int (int)'
2 warnings generated.
2 warnings generated.
2 warnings generated.
2 warnings generated.
2 warnings generated.
LLVM-AS nvptx--nvidiacl/lib/shared/vload_impl.ll.bc
/usr/bin/llvm-as: ./generic/lib/shared/vload_impl.ll:33:6: error: unexpected type in metadata definition
!1 = metadata !{metadata !"char", metadata !5}
     ^
make: *** [nvptx--nvidiacl/lib/shared/vload_impl.ll.bc] Error 1

This time, with an updated local copy of the repo.

**Comment by PhantomX** [comment]
Waiting upstream fix it.

**Comment by PhantomX** [comment]
My bad, git repo changed to http://llvm.org/git/libclc.git. Latest working is 20150419.
VERSION=20150419 ./libclc.SlackBuild

**Comment by Xylemon** [comment]
Ok I tried the latest git and the version from 20150419 and both are failing on me. The latest git version doesn't work with the patches, and even after disabling them I get this compile failure:

/usr/bin/llvm-as: ./generic/lib/subnormal_helper_func.ll:4:21: error: expected value token
  %disable = load i1, i1* @__CLC_SUBNORMAL_DISABLE
                    ^
make: *** [nvptx--nvidiacl/lib/subnormal_helper_func.ll.bc] Error 1
make: *** Waiting for unfinished jobs....
LLVM-AS nvptx--nvidiacl/lib/subnormal_helper_func.ll.bc
/usr/bin/llvm-as: ./generic/lib/subnormal_helper_func.ll:4:21: error: expected value token
  %disable = load i1, i1* @__CLC_SUBNORMAL_DISABLE
                    ^
make: *** [nvptx--nvidiacl/lib/subnormal_helper_func.ll.bc] Error 1

**Comment by PhantomX** [comment]
The snapshot script was broken, latest git is broken and patches are uneeded. Try new commit.
Remove old tarball and VERSION=20150419 ./libclc.SlackBuild

**Comment by Xylemon** [comment]
Thank you, it compiles now!
