### ISSUE TITLE
Mesa fails to compile

### ISSUE THREAD

**Issue by Xylemon** [PhantomX/slackbuilds#24]
Mesa fails to compile for me with this error:

nir/glsl_to_nir.cpp:850:1: error: expected ',' or ';' before '{' token
 {
 ^
make[3]: *** [nir/glsl_to_nir.lo] Error 1

I appear to have everything installed (except for systemd and Wayland but I removed that from the SlackBuild).

**Comment by PhantomX** [comment]
I can't help with this, because it compiles here without problems. Try update bison.

**Comment by Xylemon** [comment]
Was using the latest bison package from Slackware's FTP, so I decided to use your bison SlackBuild, now it gives a different error:

Making all in glsl
make[2]: Entering directory `/tmp/mesa-10.5.4/src/glsl'
yacc  -o glsl_parser.cpp -p "_mesa_glsl_" --defines=./glsl_parser.h glsl_parser.yy
/bin/sh: yacc: command not found
make[2]: *** [glsl_parser.cpp] Error 127

**Comment by PhantomX** [comment]
yacc is from bison. Slackware current has bison 3.0.4 for some time too.

**Comment by Xylemon** [comment]
As I stated in my previous comment, I was using the Bison 3.0.4 package from Slackware current which gave the initial error. So I tried your Bison 3.0.4 and now the error above happens. Seems weird that yacc would be missing like that...

**Comment by PhantomX** [comment]
So I'm out of ideas. What's your gcc version?

**Comment by Xylemon** [comment]
GCC 4.9.2 with multilib support from Alien Bob's repo.

**Comment by PhantomX** [comment]
So I'm really out of ideas now. :/

**Comment by Xylemon** [comment]
Really strange, I'll let you know if the situation changes...

**Comment by Xylemon** [comment]
I don't plan to compile Mesa anytime soon with my new hardware. Closing this issue since it was probably something on my end anyway.
