### ISSUE TITLE
When not using fakeroot --cleanup doesn't work

### ISSUE THREAD

**Issue by laenion** [PhantomX/slackbuilds#25]
When fakeroot is not installed the `--cleanup` command will fail: The contents of `${PKG}` is created with _root_ ownership, but the cleanup is done with user permissions - thus a cleanup will not succeed. This in turn will prevent building the package a second time, as the directory still exists and can't be written with user permissions.

I can think of two possible solutions:
1. Move the cleanup block above the block where the `${ROOTCOMMANDS}` are executed and add the purge commands to the _ROOTCOMMANDS_ variable.
2. Remove support for calling the SlackBuilds without being root or having fakeroot installed.

I have only verified this behavior with a few packages (e.g. allegro & libmirage), but is seems a lot of (if not all) packages seem to be affected by this.

**Comment by PhantomX** [comment]
All packages are affected. I will remove root password support gradually, so only full root and fakeroot will be supported. By the way, I always run with fakeroot as user.
